# Generated by Django 4.0.6 on 2022-10-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_lastname', models.CharField(max_length=50, verbose_name='Xodimni ismi va familiyasi:')),
                ('acceptance_date', models.DateField(default='', verbose_name='Kelgan sana:')),
                ('pasport', models.CharField(default='', max_length=20, verbose_name='Passport raqam:')),
                ('phone_number', models.IntegerField(verbose_name='Telefon raqam:')),
                ('science', models.CharField(max_length=30, verbose_name='Fani:')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi:')),
                ('vaqt', models.CharField(max_length=50, null=True, verbose_name='Dars vaqti:')),
                ('acceptance_date', models.DateField(verbose_name='Ochilgan sana:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Kursni narxi:')),
                ('is_close', models.BooleanField(default=False, verbose_name='Tugatish holati')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.employess', verbose_name="Biriktirilgan o'qituvchi")),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(choices=[('1', 'Qoraqalpog‘iston Respublikasi'), ('2', 'Andijon viloyati'), ('3', 'Buxoro viloyati'), ('4', 'Jizzax viloyati'), ('5', 'Qashqadaryo viloyati'), ('6', 'Navoiy viloyati'), ('7', 'Namangan viloyati'), ('8', 'Samarqand viloyati'), ('9', 'Surxandaryo viloyati'), ('10', 'Sirdaryo viloyati'), ('11', 'Toshkent viloyati'), ('12', 'Farg‘ona viloyati'), ('13', 'Xorazm viloyati'), ('14', 'Toshkent shahri')], max_length=31, verbose_name='Viloyatni tanlang:')),
                ('district', models.CharField(max_length=35, verbose_name='Tumanni kiriting:')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="O'quvchini ismi va familiyasi: ")),
                ('acceptance_date', models.DateField(verbose_name='Qabul qilingan sana:')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sana:")),
                ('phone_number', models.IntegerField(verbose_name='Telefon raqami:')),
                ('email', models.CharField(max_length=100, verbose_name='Email manzili:')),
                ('shartnoma_raqami', models.CharField(max_length=30, verbose_name='Shartnoma raqami:')),
                ('PINFL_number', models.CharField(max_length=30, verbose_name='PINFL/Passport raqami:')),
                ('region', models.CharField(choices=[('1', 'Qoraqalpog‘iston Respublikasi'), ('2', 'Andijon viloyati'), ('3', 'Buxoro viloyati'), ('4', 'Jizzax viloyati'), ('5', 'Qashqadaryo viloyati'), ('6', 'Navoiy viloyati'), ('7', 'Namangan viloyati'), ('8', 'Samarqand viloyati'), ('9', 'Surxandaryo viloyati'), ('10', 'Sirdaryo viloyati'), ('11', 'Toshkent viloyati'), ('12', 'Farg‘ona viloyati'), ('13', 'Xorazm viloyati'), ('14', 'Toshkent shahri')], max_length=31, verbose_name='Viloyatni tanlang:')),
                ('district', models.CharField(max_length=35, verbose_name='Tuman va manzilni kiriting:')),
                ('is_comleted', models.BooleanField(default=False, verbose_name='Tugatish holati')),
                ('acceptance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.groups', verbose_name='Qabul qilingan guruh:')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_period', models.DateField()),
                ('do_period', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Narxi')),
                ('freedom', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Imtiyoz:')),
                ('price_money', models.DecimalField(decimal_places=2, max_digits=50, verbose_name="To'lanishi kerak:")),
                ('status', models.BooleanField(default='False', verbose_name='Holat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.students', verbose_name="O'quvchini tanlang:")),
            ],
        ),
    ]
