# Generated by Django 4.0.6 on 2022-10-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Xodimni ismi:')),
                ('last_name', models.CharField(max_length=30, verbose_name='Xodimni familiyasi:')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi:')),
                ('vaqt', models.CharField(max_length=50, null=True, verbose_name='Dars vaqti:')),
                ('acceptance_date', models.DateField(verbose_name='Ochilgan sana:')),
                ('is_close', models.BooleanField(default=False, verbose_name='Tugatish holati')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.employess', verbose_name="Biriktirilgan o'qituvchi")),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(choices=[('1', 'Qoraqalpog‘iston Respublikasi'), ('2', 'Andijon viloyati'), ('3', 'Buxoro viloyati'), ('4', 'Jizzax viloyati'), ('5', 'Qashqadaryo viloyati'), ('6', 'Navoiy viloyati'), ('7', 'Namangan viloyati'), ('8', 'Samarqand viloyati'), ('9', 'Surxandaryo viloyati'), ('10', 'Sirdaryo viloyati'), ('11', 'Toshkent viloyati'), ('12', 'Farg‘ona viloyati'), ('13', 'Xorazm viloyati'), ('14', 'Toshkent shahri')], max_length=31, verbose_name='Viloyatni tanlang:')),
                ('district', models.CharField(max_length=35, verbose_name='Tumanni kiriting:')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="O'quvchini ismi va familiyasi: ")),
                ('acceptance_date', models.DateField(verbose_name='Qabul qilingan sana:')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sana:")),
                ('phone_number', models.IntegerField(verbose_name='Telefon raqami:')),
                ('email', models.CharField(max_length=100, verbose_name='Email manzili:')),
                ('shartnoma_raqami', models.CharField(max_length=30, verbose_name='Shartnoma raqami:')),
                ('PINFL_number', models.CharField(max_length=30, verbose_name='PINFL/Passport raqami:')),
                ('region', models.CharField(choices=[('1', 'Qoraqalpog‘iston Respublikasi'), ('2', 'Andijon viloyati'), ('3', 'Buxoro viloyati'), ('4', 'Jizzax viloyati'), ('5', 'Qashqadaryo viloyati'), ('6', 'Navoiy viloyati'), ('7', 'Namangan viloyati'), ('8', 'Samarqand viloyati'), ('9', 'Surxandaryo viloyati'), ('10', 'Sirdaryo viloyati'), ('11', 'Toshkent viloyati'), ('12', 'Farg‘ona viloyati'), ('13', 'Xorazm viloyati'), ('14', 'Toshkent shahri')], max_length=31, verbose_name='Viloyatni tanlang:')),
                ('district', models.CharField(max_length=35, verbose_name='Tuman va manzilni kiriting:')),
                ('is_comleted', models.BooleanField(default=False, verbose_name='Tugatish holati')),
                ('acceptance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.groups', verbose_name='Qabul qilingan guruh:')),
            ],
        ),
    ]
