# Generated by Django 4.0.6 on 2022-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='freedom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Imtiyozi:'),
        ),
    ]
