# Generated by Django 4.0.6 on 2022-10-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_students_freedom'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name="O'quvchini rasmi:"),
        ),
    ]
