# Generated by Django 4.0.6 on 2022-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_students_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='parol',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
