# Generated by Django 4.0.6 on 2022-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_students_parol_students_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='days',
            field=models.CharField(choices=[('1', 'Har kuni'), ('2', 'Juft kunlar'), ('3', 'Toq kunlar')], default=1, max_length=12, verbose_name='Dars kunlarini tanlang:'),
            preserve_default=False,
        ),
    ]
