# Generated by Django 4.0.6 on 2022-11-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_groups_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='Dars davomiyligi: '),
            preserve_default=False,
        ),
    ]
